git actions workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -238,12 +238,18 @@ jobs:
           cd modules
           
           echo "Running terraform output for artifacts_bucket_name"
-          ARTIFACTS=$(terraform output -json artifacts_bucket_name)
+          if ! ARTIFACTS=$(terraform output -json artifacts_bucket_name); then
+            echo "Failed to get artifacts_bucket_name"
+            exit 1
+          fi
           ARTIFACTS_BUCKET_NAME=$(echo "$ARTIFACTS" | jq -r '.' | tr -d '\n')
           echo "ARTIFACTS_BUCKET_NAME=${ARTIFACTS_BUCKET_NAME}"
 
           echo "Running terraform output for namespace"
-          NAMESPACE_ARTIFACTS=$(terraform output -json namespace)
+          if ! NAMESPACE_ARTIFACTS=$(terraform output -json namespace); then
+            echo "Failed to get namespace"
+            exit 1
+          fi
           NAMESPACE=$(echo "$NAMESPACE_ARTIFACTS" | jq -r '.' | tr -d '\n')
           echo "NAMESPACE=${NAMESPACE}"
 
@@ -252,7 +258,6 @@ jobs:
             ${{ github.workspace }}/bin/build_artifacts.zip \
             ${NAMESPACE} \
             ${ARTIFACTS_BUCKET_NAME}
-
       # Functional Tests
       - name: Functional Tests
         run: |
